// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package coolbeans_api_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JobStateProto int32

const (
	JobStateProto_INITIAL  JobStateProto = 0
	JobStateProto_READY    JobStateProto = 1
	JobStateProto_RESERVED JobStateProto = 2
	JobStateProto_BURIED   JobStateProto = 3
	JobStateProto_DELAYED  JobStateProto = 4
	JobStateProto_DELETED  JobStateProto = 5
)

var JobStateProto_name = map[int32]string{
	0: "INITIAL",
	1: "READY",
	2: "RESERVED",
	3: "BURIED",
	4: "DELAYED",
	5: "DELETED",
}

var JobStateProto_value = map[string]int32{
	"INITIAL":  0,
	"READY":    1,
	"RESERVED": 2,
	"BURIED":   3,
	"DELAYED":  4,
	"DELETED":  5,
}

func (x JobStateProto) String() string {
	return proto.EnumName(JobStateProto_name, int32(x))
}

func (JobStateProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

type JobProto struct {
	// Unique identifier for job
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Priority is an integer < 2**32. Jobs with smaller priority values will be
	// scheduled before jobs with larger priorities. The most urgent priority is 0;
	// the least urgent priority is 4,294,967,295.
	Priority uint32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// delay is an integer number of seconds to wait before putting the job in
	// the ready queue. The job will be in the "delayed" state during this time.
	// Maximum delay is 2**32-1.
	Delay int64 `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	// TTR/time to run -- is an integer number of seconds to allow a worker
	// to run this job. This time is counted from the moment a worker reserves
	// this job. If the worker does not delete, release, or bury the job within
	// <ttr> seconds, the job will time out and the server will release the job.
	// The minimum ttr is 1. If the client sends 0, the server will silently
	// increase the ttr to 1. Maximum ttr is 2**32-1.
	Ttr int32 `protobuf:"varint,4,opt,name=ttr,proto3" json:"ttr,omitempty"`
	// tube_name is the name of the tube associated with this job
	TubeName string `protobuf:"bytes,5,opt,name=tube_name,json=tubeName,proto3" json:"tube_name,omitempty"`
	// created is the time in UTC the job is created
	CreatedAt int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ready_at is the time in UTC the job is ready
	ReadyAt int64 `protobuf:"varint,7,opt,name=ready_at,json=readyAt,proto3" json:"ready_at,omitempty"`
	// expires_at is the time in UTC, when current reservation expires
	ExpiresAt int64 `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// state is the current state of this job
	State JobStateProto `protobuf:"varint,9,opt,name=state,proto3,enum=coolbeans.api.v1.JobStateProto" json:"state,omitempty"`
	// reserved_by is the identifier of the client which has
	// reserved this job, the value is empty if un-reserved
	ReservedBy string `protobuf:"bytes,10,opt,name=reserved_by,json=reservedBy,proto3" json:"reserved_by,omitempty"`
	// body_size is an integer indicating the size of the job body, not including the
	// trailing "\r\n". This value must be less than max-job-size (default: 2**16)
	BodySize int32 `protobuf:"varint,11,opt,name=body_size,json=bodySize,proto3" json:"body_size,omitempty"`
	// body is the job body -- a sequence of bytes of length BodySize
	Body                 []byte   `protobuf:"bytes,12,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobProto) Reset()         { *m = JobProto{} }
func (m *JobProto) String() string { return proto.CompactTextString(m) }
func (*JobProto) ProtoMessage()    {}
func (*JobProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *JobProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobProto.Unmarshal(m, b)
}
func (m *JobProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobProto.Marshal(b, m, deterministic)
}
func (m *JobProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobProto.Merge(m, src)
}
func (m *JobProto) XXX_Size() int {
	return xxx_messageInfo_JobProto.Size(m)
}
func (m *JobProto) XXX_DiscardUnknown() {
	xxx_messageInfo_JobProto.DiscardUnknown(m)
}

var xxx_messageInfo_JobProto proto.InternalMessageInfo

func (m *JobProto) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobProto) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *JobProto) GetDelay() int64 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *JobProto) GetTtr() int32 {
	if m != nil {
		return m.Ttr
	}
	return 0
}

func (m *JobProto) GetTubeName() string {
	if m != nil {
		return m.TubeName
	}
	return ""
}

func (m *JobProto) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *JobProto) GetReadyAt() int64 {
	if m != nil {
		return m.ReadyAt
	}
	return 0
}

func (m *JobProto) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *JobProto) GetState() JobStateProto {
	if m != nil {
		return m.State
	}
	return JobStateProto_INITIAL
}

func (m *JobProto) GetReservedBy() string {
	if m != nil {
		return m.ReservedBy
	}
	return ""
}

func (m *JobProto) GetBodySize() int32 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

func (m *JobProto) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("coolbeans.api.v1.JobStateProto", JobStateProto_name, JobStateProto_value)
	proto.RegisterType((*JobProto)(nil), "coolbeans.api.v1.JobProto")
}

func init() {
	proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead)
}

var fileDescriptor_f32c477d91a04ead = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcf, 0x8a, 0xd4, 0x30,
	0x18, 0x37, 0xed, 0x74, 0xa6, 0xfd, 0x66, 0x76, 0x09, 0xc1, 0x43, 0x54, 0x64, 0x8b, 0xa7, 0xe2,
	0xa1, 0xa0, 0xe2, 0x03, 0x74, 0x69, 0x0e, 0x5d, 0x96, 0x45, 0x32, 0xab, 0xb0, 0x78, 0x28, 0xc9,
	0xf6, 0x3b, 0x44, 0x76, 0x26, 0x25, 0x8d, 0x83, 0x9d, 0x77, 0xf5, 0x5d, 0x24, 0x99, 0x51, 0x70,
	0x6f, 0xbf, 0xbf, 0x49, 0x7e, 0x04, 0x8a, 0x1f, 0x56, 0xd7, 0xa3, 0xb3, 0xde, 0x32, 0xfa, 0x68,
	0xed, 0x93, 0x46, 0xb5, 0x9f, 0x6a, 0x35, 0x9a, 0xfa, 0xf0, 0xe1, 0xdd, 0xef, 0x04, 0xf2, 0x1b,
	0xab, 0xbf, 0x44, 0xfb, 0x12, 0x12, 0x33, 0x70, 0x52, 0x92, 0x2a, 0x95, 0x89, 0x19, 0xd8, 0x6b,
	0xc8, 0x47, 0x67, 0xac, 0x33, 0x7e, 0xe6, 0x49, 0x49, 0xaa, 0x0b, 0xf9, 0x8f, 0xb3, 0x97, 0x90,
	0x0d, 0xf8, 0xa4, 0x66, 0x9e, 0xc6, 0xf8, 0x89, 0x30, 0x0a, 0xa9, 0xf7, 0x8e, 0x2f, 0x4a, 0x52,
	0x65, 0x32, 0x40, 0xf6, 0x06, 0x0a, 0xff, 0x53, 0x63, 0xbf, 0x57, 0x3b, 0xe4, 0x59, 0x49, 0xaa,
	0x42, 0xe6, 0x41, 0xb8, 0x53, 0x3b, 0x64, 0x6f, 0x01, 0x1e, 0x1d, 0x2a, 0x8f, 0x43, 0xaf, 0x3c,
	0x5f, 0xc6, 0x93, 0x8a, 0xb3, 0xd2, 0x78, 0xf6, 0x0a, 0x72, 0x87, 0x6a, 0x98, 0x83, 0xb9, 0x8a,
	0xe6, 0x2a, 0xf2, 0xc6, 0x87, 0x26, 0xfe, 0x1a, 0x8d, 0xc3, 0x29, 0x98, 0xf9, 0xa9, 0x79, 0x56,
	0x1a, 0xcf, 0x3e, 0x43, 0x36, 0x79, 0xe5, 0x91, 0x17, 0x25, 0xa9, 0x2e, 0x3f, 0x5e, 0xd5, 0xcf,
	0x87, 0xd7, 0x37, 0x56, 0x6f, 0x43, 0x22, 0x2e, 0x97, 0xa7, 0x34, 0xbb, 0x82, 0xb5, 0xc3, 0x09,
	0xdd, 0x01, 0x87, 0x5e, 0xcf, 0x1c, 0xe2, 0x73, 0xe1, 0xaf, 0x74, 0x3d, 0x87, 0x35, 0xda, 0x0e,
	0x73, 0x3f, 0x99, 0x23, 0xf2, 0x75, 0x5c, 0x99, 0x07, 0x61, 0x6b, 0x8e, 0xc8, 0x18, 0x2c, 0x02,
	0xe6, 0x9b, 0x92, 0x54, 0x1b, 0x19, 0xf1, 0xfb, 0xef, 0x70, 0xf1, 0xdf, 0x4d, 0x6c, 0x0d, 0xab,
	0xee, 0xae, 0xbb, 0xef, 0x9a, 0x5b, 0xfa, 0x82, 0x15, 0x90, 0x49, 0xd1, 0xb4, 0x0f, 0x94, 0xb0,
	0x0d, 0xe4, 0x52, 0x6c, 0x85, 0xfc, 0x26, 0x5a, 0x9a, 0x30, 0x80, 0xe5, 0xf5, 0x57, 0xd9, 0x89,
	0x96, 0xa6, 0xa1, 0xd1, 0x8a, 0xdb, 0xe6, 0x41, 0xb4, 0x74, 0x71, 0x26, 0xe2, 0x5e, 0xb4, 0x34,
	0xd3, 0xcb, 0xf8, 0xab, 0x9f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x1c, 0x38, 0x45, 0xe2,
	0x01, 0x00, 0x00,
}
