// Code generated by "stringer -type=CmdType --output cmd_type_string.go"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Bury-1]
	_ = x[Delete-2]
	_ = x[Ignore-3]
	_ = x[Kick-4]
	_ = x[KickJob-5]
	_ = x[ListTubes-6]
	_ = x[ListTubeUser-7]
	_ = x[PauseTube-8]
	_ = x[Peek-9]
	_ = x[PeekBuried-10]
	_ = x[PeekDelayed-11]
	_ = x[PeekReady-12]
	_ = x[Put-13]
	_ = x[Quit-14]
	_ = x[Release-15]
	_ = x[Reserve-16]
	_ = x[ReserveJob-17]
	_ = x[ReserveWithTimeout-18]
	_ = x[Stats-19]
	_ = x[StatsJob-20]
	_ = x[StatsTube-21]
	_ = x[Touch-22]
	_ = x[Use-23]
	_ = x[Watch-24]
	_ = x[Max-25]
}

const _CmdType_name = "UnknownBuryDeleteIgnoreKickKickJobListTubesListTubeUserPauseTubePeekPeekBuriedPeekDelayedPeekReadyPutQuitReleaseReserveReserveJobReserveWithTimeoutStatsStatsJobStatsTubeTouchUseWatchMax"

var _CmdType_index = [...]uint8{0, 7, 11, 17, 23, 27, 34, 43, 55, 64, 68, 78, 89, 98, 101, 105, 112, 119, 129, 147, 152, 160, 169, 174, 177, 182, 185}

func (i CmdType) String() string {
	if i < 0 || i >= CmdType(len(_CmdType_index)-1) {
		return "CmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CmdType_name[_CmdType_index[i]:_CmdType_index[i+1]]
}
