version: "3.7"

services:
  bean1:
    build: .
    ports:
      - "127.0.0.1:12000:12000/tcp"
    networks:
      - cb_network
    command: ["/root/coolbeans", "cluster-node",  "--node-id", "bean1", 
      "--root-dir", "/tmp/bean1", 
      "--bootstrap-node-id", "bean0", 
      "--node-peer-addrs", "bean0:11000,bean1:12000,bean2:13000",
      "--raft-listen-addr", "bean1:22000",
      "--node-listen-addr", "bean1:12000",
      "--raft-advertized-addr=bean3:22000"]

  bean0:
    build: .
    ports:
      - "127.0.0.1:11000:11000/tcp"
    networks:
      - cb_network
    command: ["/root/coolbeans", "cluster-node",  "--node-id", "bean0", 
      "--root-dir", "/tmp/bean", 
      "--bootstrap-node-id", "bean0", 
      "--node-peer-addrs", "bean0:11000,bean1:12000,bean2:13000",
      "--raft-listen-addr", "bean0:21000",
      "--node-listen-addr", "bean0:11000",
      "--raft-advertized-addr=bean0:21000"]

  bean2:
    build: .
    ports:
      - "127.0.0.1:13000:13000/tcp"
    networks:
      - cb_network
    command: ["/root/coolbeans", "cluster-node",  
      "--node-id", "bean2", 
      "--root-dir", "/tmp/bean", 
      "--bootstrap-node-id", "bean0", 
      "--node-peer-addrs", "bean0:11000,bean1:12000,bean2:13000",
      "--raft-listen-addr=bean2:23000",
      "--node-listen-addr=bean2:13000",
      "--raft-advertized-addr=bean2:23000"]

  beanstalkd-proxy0:
    build: .
    ports:
      - "127.0.0.1:11300:11300/tcp"
    networks:
      - cb_network
    command: ["/root/coolbeans", 
      "beanstalkd",  
      "-p", "11300", 
      "-j", "bean0:11000,bean1:12000,bean2:13000"]

networks:
  cb_network: