// Code generated by "stringer -type=JobState --output state_string.go"; DO NOT EDIT.

package state

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Initial-0]
	_ = x[Ready-1]
	_ = x[Reserved-2]
	_ = x[Buried-3]
	_ = x[Delayed-4]
	_ = x[Deleted-5]
}

const _JobState_name = "InitialReadyReservedBuriedDelayedDeleted"

var _JobState_index = [...]uint8{0, 7, 12, 20, 26, 33, 40}

func (i JobState) String() string {
	if i < 0 || i >= JobState(len(_JobState_index)-1) {
		return "JobState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _JobState_name[_JobState_index[i]:_JobState_index[i+1]]
}
