// Code generated by "stringer -type=ConnState"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WantCommand-0]
	_ = x[ReadyToProcess-1]
	_ = x[WantData-2]
	_ = x[SendJob-3]
	_ = x[SendWord-4]
	_ = x[WaitReservation-5]
	_ = x[BitBucket-6]
	_ = x[Close-7]
	_ = x[WantEndLine-8]
	_ = x[Stopped-9]
}

const _ConnState_name = "WantCommandReadyToProcessWantDataSendJobSendWordWaitReservationBitBucketCloseWantEndLineStopped"

var _ConnState_index = [...]uint8{0, 11, 25, 33, 40, 48, 63, 72, 77, 88, 95}

func (i ConnState) String() string {
	if i < 0 || i >= ConnState(len(_ConnState_index)-1) {
		return "ConnState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnState_name[_ConnState_index[i]:_ConnState_index[i+1]]
}
