name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@master
      with:
        version: '3.11.4'      

    - name: Set up Go 1.13+
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16.3
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: UnitTests
      run: make test

    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_PASS }}' | docker login --username 1xyz --password-stdin

    - name: Docker build and push
      run: make docker-push